Attempt to satisfy Windows Build Error
The check on Windows stated that an error happened while processing because the there was no package RForcecom, which should not be the case

Error: Error: processing vignette 'transitioning-from-RForcecom.Rmd' failed with diagnostics:

there is no package called 'RForcecom'

https://github.com/StevenMMortimer/salesforcer/runs/2985296515?check_suite_focus=true